language: java
jdk:
  - oraclejdk8
install: true
script:
  - mvn install
after_success:
  - mkdir push
  - cp ./target/*.jar ./push/
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: $Github_token
  file:
    - ./push/*
  file_glob: true
  on:
    tags: true